import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import ResponsiveAppBar from "@/components/Navbar";
import { Sidebar } from "@/components/sidebar";
import styles from "./layout.module.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          {/* <ResponsiveAppBar /> */}
          <div
            style={{
              display: "flex",
              gap: "2rem",
            }}
          >
            <Sidebar />
            {/* <main className={styles.main}> */}
              {children}
              
              {/* </main> */}
          </div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
